// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {params} from '../models';

export function CreateUser(arg1:string):Promise<void>;

export function GetMessages():Promise<Array<params.Message>>;

export function Send(arg1:string):Promise<string>;
