name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-wails:
    name: Build wails
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: windows-latest
          #   platform: windows/amd64
          #   output: wachat-windows.exe
          - os: macos-latest
            platform: darwin/universal
            # wails bug, mac outputfile name not work
            output: wachat
          - os: ubuntu-20.04
            platform: linux/amd64
            output: wachat-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install libpcsclite
        if: matrix.platform == 'linux/amd64'
        run: sudo apt install libpcsclite-dev
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install && npm run build
        working-directory: frontend
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.output }}
          build-platform: ${{ matrix.platform }}
          go-version: 1.20.x
          package: false
      - if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -rf ./build/bin/${{ matrix.output }}.app.zip
          ditto -c -k --keepParent ./build/bin/${{matrix.output}}.app ./build/bin/wachat.app.zip
          rm -rf ./build/bin/${{ matrix.output }}.app

      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: build/bin/*

  collect-release:
    name: Collect and release
    needs: [ build-wails ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: ls -al target && ls -R target/
      - working-directory: target
        run: |
          rm -rf wachat-amd64-installer.exe
          rm -rf wachat.pkg
          mv wachat.app.zip wachat-darwin.app.zip
      - run: ls -al target && ls -R target/ && file target/
      - uses: actions/upload-artifact@v3
        with:
          name: target-release
          path: target/*

      # release assets
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*
